package com.saveslot.app.domain.discover

/**
 * Curated seed titles for the discovery rail.
 *
 * There is no public "interesting games" endpoint, so discovery is driven by a hand-picked list
 * spanning generations, genres and regions. Entries carry a disambiguating suffix
 * ("Ico", "Rez video game") where the bare title would resolve to a film, album or person.
 */
internal object DiscoverSeeds {
    val TITLES: List<String> = listOf(
        "The Legend of Zelda: Link's Awakening",
        "Vagrant Story",
        "Panzer Dragoon Saga",
        "Jet Set Radio",
        "Silent Hill 2",
        "Gravity Rush",
        "Hotel Dusk: Room 215",
        "The World Ends with You",
        "Ico",
        "Skies of Arcadia",
        "EarthBound",
        "Another World video game",
        "System Shock 2",
        "Klonoa: Door to Phantomile",
        "The Last Guardian",
        "Outer Wilds",
        "Metroid: Zero Mission",
        "Shin Megami Tensei: Strange Journey",
        "Chibi-Robo!",
        "Lost Odyssey",
        "Rule of Rose",
        "Terranigma",
        "Koudelka",
        "A Short Hike",
        "Ghost Trick: Phantom Detective",
        "Beyond the Labyrinth video game",
        "The Legend of Zelda: Majora's Mask",
        "Okami video game",
        "Rez video game",
        "Parasite Eve video game",
        "Chrono Trigger",
        "Chrono Cross",
        "Final Fantasy Tactics",
        "Final Fantasy IX",
        "Xenogears",
        "Xenoblade Chronicles",
        "Suikoden II",
        "Persona 4",
        "Persona 5",
        "Digital Devil Saga",
        "Demon’s Souls",
        "Dark Souls",
        "Bloodborne",
        "Sekiro: Shadows Die Twice",
        "Castlevania: Symphony of the Night",
        "Super Metroid",
        "Metroid Prime",
        "The Legend of Zelda: The Wind Waker",
        "The Legend of Zelda: Twilight Princess",
        "The Legend of Zelda: A Link to the Past",
        "The Legend of Zelda: The Minish Cap",
        "Mother 3",
        "Paper Mario: The Thousand-Year Door",
        "Super Mario Galaxy",
        "Super Mario Sunshine",
        "Donkey Kong Country 2",
        "Yoshi’s Island",
        "Kirby: Planet Robobot",
        "F-Zero GX",
        "Wave Race 64",
        "Ridge Racer Type 4",
        "Wipeout 3",
        "Burnout 3: Takedown",
        "Need for Speed: Underground 2",
        "Gran Turismo 4",
        "Forza Horizon",
        "Metal Gear Solid",
        "Metal Gear Solid 2: Sons of Liberty",
        "Metal Gear Solid 3: Snake Eater",
        "Splinter Cell: Chaos Theory",
        "Resident Evil 2",
        "Resident Evil 4",
        "Silent Hill",
        "Fatal Frame II: Crimson Butterfly",
        "Haunting Ground",
        "Clock Tower video game",
        "Dead Space",
        "Alien: Isolation",
        "BioShock",
        "Prey 2017 video game",
        "Deus Ex",
        "Thief II: The Metal Age",
        "Dishonored",
        "Half-Life 2",
        "Portal 2",
        "Mirror’s Edge",
        "Prince of Persia: The Sands of Time",
        "Beyond Good & Evil",
        "Psychonauts",
        "Sly 2: Band of Thieves",
        "Jak and Daxter: The Precursor Legacy",
        "Ratchet & Clank: Up Your Arsenal",
        "Viewtiful Joe",
        "God Hand video game",
        "Okage: Shadow King",
        "Radiata Stories",
        "Baten Kaitos: Eternal Wings and the Lost Ocean",
        "The Last Story",
        "Pandora’s Tower",
        "NieR video game",
        "NieR: Automata",
        "13 Sentinels: Aegis Rim",
        "Odin Sphere",
        "Muramasa: The Demon Blade",
        "Catherine video game",
        "Professor Layton and the Curious Village",
        "Ace Attorney: Phoenix Wright",
        "999: Nine Hours, Nine Persons, Nine Doors",
        "Zero Escape: Virtue’s Last Reward",
        "Danganronpa: Trigger Happy Havoc",
        "AI: The Somnium Files",
        "Return of the Obra Dinn",
        "Disco Elysium",
        "Pentiment",
        "Tunic video game",
        "Cocoon video game",
        "Inside video game",
        "Limbo video game",
        "Journey video game",
        "Abzû",
        "Gris video game",
        "Hollow Knight",
        "Celeste video game",
        "Fez video game",
        "Hyper Light Drifter",
        "Katana Zero",
        "Hotline Miami",
        "Transistor video game",
        "Bastion video game",
        "Hades video game",
        "Into the Breach",
        "FTL: Faster Than Light",
        "Slay the Spire",
        "Inscryption",
        "Balatro video game",
    )
}
